### ISSUE TITLE
When typing "/execute as @e[nbt=" game crashes

### ISSUE THREAD

**Issue by kurait** [mt1006/mc-nbtac-mod#39]
### Crash Log:

```
---- Minecraft Crash Report ----
// There are four lights!

Time: 2024-11-19 10:03:36
Description: charTyped event handler

java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because "name" is null
	at knot//com.mt1006.nbt_ac.autocomplete.NbtSuggestionManager.loadFromName(NbtSuggestionManager.java:51)
	at knot//net.minecraft.class_2303.suggestNbt(class_2303.java:1219)
	at knot//net.minecraft.class_2303.method_9908(class_2303.java:500)
	at knot//net.minecraft.class_2186.listSuggestions(class_2186.java:126)
	at knot//com.mojang.brigadier.tree.ArgumentCommandNode.listSuggestions(ArgumentCommandNode.java:69)
	at knot//com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:599)
	at knot//net.minecraft.class_4717.method_23934(class_4717.java:186)
	at knot//net.minecraft.class_408.method_23945(class_408.java:84)
	at knot//net.minecraft.class_342.method_1874(class_342.java:148)
	at knot//net.minecraft.class_342.method_1867(class_342.java:143)
	at knot//net.minecraft.class_342.method_25400(class_342.java:354)
	at knot//net.minecraft.class_4069.method_25400(class_4069.java:86)
	at knot//net.minecraft.class_309.method_1458(class_309.java:467)
	at knot//net.minecraft.class_437.method_25412(class_437.java:409)
	at knot//net.minecraft.class_309.method_1457(class_309.java:467)
	at knot//net.minecraft.class_309.method_22677(class_309.java:478)
	at knot//net.minecraft.class_1255.execute(class_1255.java:102)
	at knot//net.minecraft.class_309.method_22675(class_309.java:478)
	at knot//org.lwjgl.glfw.GLFWCharModsCallbackI.callback(GLFWCharModsCallbackI.java:46)
	at knot//org.lwjgl.system.JNI.invokeV(Native Method)
	at knot//org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at knot//com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:201)
	at knot//com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:219)
	at knot//net.minecraft.class_1041.method_15998(class_1041.java:288)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1241)
	at knot//net.minecraft.class_310.method_1514(class_310.java:802)
	at knot//net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:105)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at knot//com.mt1006.nbt_ac.autocomplete.NbtSuggestionManager.loadFromName(NbtSuggestionManager.java:51)
	at knot//net.minecraft.class_2303.suggestNbt(class_2303.java:1219)
	at knot//net.minecraft.class_2303.method_9908(class_2303.java:500)
	at knot//net.minecraft.class_2186.listSuggestions(class_2186.java:126)
	at knot//com.mojang.brigadier.tree.ArgumentCommandNode.listSuggestions(ArgumentCommandNode.java:69)
	at knot//com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:599)
	at knot//net.minecraft.class_4717.method_23934(class_4717.java:186)
	at knot//net.minecraft.class_408.method_23945(class_408.java:84)
	at knot//net.minecraft.class_342.method_1874(class_342.java:148)
	at knot//net.minecraft.class_342.method_1867(class_342.java:143)
	at knot//net.minecraft.class_342.method_25400(class_342.java:354)
	at knot//net.minecraft.class_4069.method_25400(class_4069.java:86)
	at knot//net.minecraft.class_309.method_1458(class_309.java:467)
	at knot//net.minecraft.class_437.method_25412(class_437.java:409)
	at knot//net.minecraft.class_309.method_1457(class_309.java:467)
	at knot//net.minecraft.class_309.method_22677(class_309.java:478)
	at knot//net.minecraft.class_1255.execute(class_1255.java:102)
	at knot//net.minecraft.class_309.method_22675(class_309.java:478)
	at knot//org.lwjgl.glfw.GLFWCharModsCallbackI.callback(GLFWCharModsCallbackI.java:46)
	at knot//org.lwjgl.system.JNI.invokeV(Native Method)
	at knot//org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at knot//com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:201)
	at knot//com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:219)

```

**Comment by mt1006** [comment]
Thanks for reporting, I'll fix it soon.
